### ISSUE TITLE
PopupButtons is array

### ISSUE THREAD

**Issue by bas1328** [matvejs16/telegram-webapps-types-new#3]
https://github.com/matvejs16/telegram-webapps-types-new/blob/ff5f64b77a8501f47cee2028abcf9d2887ee7078/dist/index.d.ts#L485

Hi! Minor issue in types: buttons in popupParams are an array.

https://core.telegram.org/bots/webapps#popupparams

thanx for the package, btw :)

**Comment by matvejs16** [comment]
Published v1.0.3
Check if everything is ok

**Comment by bas1328** [comment]
That was quick :) appreciate it
